---
title: Introduction
format:
  html:
    other-links:
      - text: Case study brief
        href: resources/ukrn-recognition-casestudy.pdf
        target: _blank
        icon: file-earmark-pdf
---

These case studies illustrate different aspects of implementing change to enable recognition and reward for open research within research-performing organisations. They are provided by institutions that have participated in the OR4 project, and are designed to complement the [implementation guide](https://recognition.ukrn-openresearch.ac.uk/guide-contents.html). Each case study is linked to the section of the implementation guide which it mainly illustrates, although case studies naturally bear on many different aspects of institutional action discussed in the guide. 

Institutional policy and practice in this area is in many cases at an early stage, as the OR4 project's 2023 [survey of UK institutions](https://doi.org/10.31219/osf.io/z52cn) established. We are working with a number of  institutions in the OR4 community of practice to develop and publish case studies. 

## Share your case study

If you have an example of institutional activity to develop recognition and reward for open research, we would love to hear from you.

We welcome proposals for case studies from higher education and research institutions, wherever you are, whether you are taking your first steps to develop strategic action or have examples of mature practice to share. We will give you a platform to showcase your initiative and leadership in open research and to share good practice with the community. We are happy to have a conversation with you to discuss activity at your institution and to help you develop your case study. You can write up a case study and submit it to us, or we can develop a case study in conversation with you. 

If you are interested in providing a case study for the toolkit, please follow these steps:

1. Review the case study brief provided here to check your case study will be a fit for this resource. 
2. Send us a brief proposal for a case study, indicating which section(s) of the [implementation guide](https://recognition.ukrn-openresearch.ac.uk/guide-contents.html) you believe it would primarily illustrate.
3. We will review the proposal to check that it meets our criteria and may invite you to discuss it with us.
4. Further to consideration we will invite you to submit a draft of the case study using the template provided in the case study brief, or arrange a conversation with you to develop the case study.

To submit a case study proposal and for all other enquiries please contact [Evangeline Gowie](mailto:e.gowie@reading.ac.uk).

October 2024


