---
page-navigation: true
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    other-links:
      - text: This page as PDF
        href: resources/case-study-swansea.pdf
        target: _blank
        icon: file-earmark-pdf
---

# Reformed Research Assessment and Recognising Open Research in Academic Career Progression at Swansea University

**Anna Seager** (Research Culture Manager)

See Implementation guide section: [Policy and Procedure](https://recognition.ukrn-openresearch.ac.uk/guide-05-policy.html)

## About Swansea University

Swansea University is a research-intensive university with over 20,000 students and over 3,000 staff members. The university is home to three faculties covering a broad range of disciplines located across two campuses.

## What has changed? 

Beginning in September 2024, Swansea University has implemented its reformed [Academic Career Pathways (ACPs)](https://www.swansea.ac.uk/jobs-at-swansea/performance-enabling/academic-career-pathways/) and Research Assessment for staff applying for academic promotion. This change began in 2022 when Swansea University began revising its Academic Career Pathways (ACPs) and Research Assessment, retiring traditional quantitative KPIs from the assessment criteria, in a move towards more qualitative judgement. The new ACPs and Research Assessment criteria aim to better recognise impactful, quality, and innovative contributions and outputs by academic staff. The reformed process utilises a narrative-CV format, aligned with the UKRI Résumé for Research and Innovation (R4RI)-like Narrative CV. Demonstration of Research Contribution for the Academic Promotion Pathways is defined within the following four domains:

1. Contribution to the generation of knowledge 
2. Contribution to the development of individuals 
3. Contribution to the wider research and innovation community 
4. Contribution to broader society

The reformed ACPs include recognition of Open Research and Collaboration for the first time, promoting practices which support collegiality, transparency, reproducibility, and open access research.
## Why was the change undertaken?

As part of Swansea University’s promise to advance research assessment and establish an open, effective, and inclusive research culture, Swansea University joined the Coalition for Advancing Research Assessment (CoARA) as a signatory in November 2022. Swansea University holds a long history of commitment to the advancement of research assessment, having been signatories for the Concordat for Researchers since 1996, and the San Francisco Declaration of Research Assessment (DORA) since 2018. As of 2024, Swansea University co-leads the UK National Chapter of CoARA alongside University of Strathclyde and Loughborough University. In June 2024, Swansea University published its [CoARA Action Plan]((https://zenodo.org/records/12734220)) detailing its proposed actions towards from 2023 to 2028.

## How was the change carried out?
When Swansea University began the review of its ACPs and Research Assessment, a Working Group was established. It comprised of senior stakeholders from across the university, including PVCs for Research and Innovation and Education. The new career pathways were developed in close alignment to the four modules of the UKRI Resumé for Research and Innovation (R4RI). The previous ACPs included various quantitative Indicative Performance Levels, for research, innovation, education, and the student experience. The reformed process has retired these Indicative Performance Levels, acknowledging that these narrow indicators may lack the scope to adequately recognise the diverse range of achievements in research and wider academic activities.

Subgroups were established to consider principles and draft revised criteria. These subgroups consisted of colleagues from across the disciplines, at all career stages and those who were principally focused on research, education, or innovation. Co-development was a core principle, and recommendations from subgroups were brought to the main panel for review and sign off.

The university is currently undertaking a study, funded by CoARA, to evaluate the impact of these changes to the academic promotion process. The study seeks to understand the effects of the reformed process on both applicants and reviewers, to make its findings openly available for metascience on the use of narrative CVs in academic promotion assessment, and specifically understand how Open Research practices were used to demonstrate research capacity within the application. Additionally, Swansea University has established a mentoring programme for academic staff applying for promotion, providing guidance to applicants by staff members who have recently been successful in their promotion applications, in order to better support applicants through the promotion process.

## Challenges and lessons learnt
The need to accommodate a wide range of disciplinary perspectives meant that engagement from across teams was essential for the project to be successful. Early workshops on defining the criteria helped to secure a high degree of buy in, and ensure that the language used in the criteria was recognisable by all, irrespective of disciplinary background or focus area.

The first promotions round following the approval of the revised ACPs presented a further challenge: supporting colleagues in navigating new criteria and pathways. A series of webinars and Q&A sessions, together with training for faculty promotions panels, enabled transition between pathways.

One continuing area of development concerns understanding of narrative evidence. we are presently reviewing what further guidance (if any) should be given to applicants and panelists about what constitutes narrative evidence.

## Recommendations

- Engage with academic staff throughout the review process; encourage feedback on the current processes to understand what works and what can be improved, and how the proposed actions could address deficiencies.

- Keep stakeholders in all disciplines informed on open research practices, emphasizing inclusivity, transparency, and accessibility.

- Adopting a mentorship programme for academic staff applying for promotion may be a and positive and effective way to provide support and advice to applicants from staff who have successfully achieved their own academic promotions in recent years.

© Swansea University. Licensed under [CC BY](https://creativecommons.org/licenses/by/4.0/deed.en).
