---
page-navigation: true
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    other-links:
      - text: This page as PDF
        href: resources/case-study-bristol.pdf
        target: _blank
        icon: file-earmark-pdf
---

# Including open research in the University of Bristol's Academic Promotions Framework

```{=html}
<a href="resources/case-study-bristol.pdf"
   class="pdf-download" target="_blank"></a>
```

See Implementation guide section: [Policy and procedure](https://recognition.ukrn-openresearch.ac.uk/guide-05-policy.html)

## About the University of Bristol

The University of Bristol is a research-intensive University, with over 29,000 students and employing approximately 9,000 staff. The University has a reputation for academic excellence and delivering world-leading research.

## What has changed? 

A review of promotion and progression in 2017 included recommendations to review the promotion criteria for Associate Professor and Professor, which resulted in a new [Academic Promotions Framework](https://www.bristol.ac.uk/hr/policies/promotion/) (APF) that launched in the 2020-2021 academic year. The APF looks to nurture individual and team excellence through clear descriptions of the full range of contributions and achievements that are valued by our institution. This exercise resulted in the specific inclusion of open research practices as an example of the contributions recognised by the APF.

The APF provides four categories for applicants for promotion to demonstrate their achievements against: (1) Research (2) Education (3) Engagement & Impact (4) Leadership & Citizenship. Each has different criteria intended to cover the range of expectations and experiences across academic pathways, and the diversity of staff that work at the University.

The Research category captures what it takes to build our position as one of the world's leading research-intensive universities. Criterion R-1 (Research Outputs) goes beyond just publications and other formal ways of presenting research findings, and explicitly includes open research outputs. 

For an individual to be recognised for demonstrating open research outputs within the R-1 criterion, they must evidence: 'Producing open research outputs as appropriate by adopting good practice in, for example, sharing data and code, sharing materials, sharing digital outputs, publishing preprints and pre-registering study protocols'. 

## Why was the change undertaken?

As a founding member of UKRN, and lead organisation on the UKRN Open Research Programme, we recognised the need to demonstrate sectoral leadership to incentivise uptake of open research practices. Through the Research Improvement Group (now Research Culture Committee), chaired by Professor Marcus Munafò as UKRN Institutional Lead for Bristol, we liaised with those undertaking work on the development of a new Academic Promotions Framework.

The aim of the Academic Promotions Framework programme was to create an academic career path that is challenging, rewarding and inclusive, and which enables all academic staff to have the opportunity to reach their full potential.

In order to achieve this, the University needed to recognise and reward the full range of contributions and achievements that are valued by the institution in ways that are transparent, accessible and sustainable. 
At the same time, our role in UKRN and our long history of sectoral leadership on open research practices meant that the Academic Promotion Framework programme presented an opportunity to embed incentives to promote uptake of these practices.

## How was the change carried out?

The Deputy Vice Chancellor and Provost was the senior sponsor of the Academic Promotion Framework programme, and chaired a Programme Board made up of senior stakeholders across the institution. Having a senior sponsor for the change was imperative to promote the strategic importance of creating the APF, and in navigating resistance to the change in the process. 

The facilitators and Programme Managers of the change were the Academic Staff Development team, operating as part of the Academic Career Development Programme. The University's commitment to external agreements such as DORA and the Concordat on Open Research Data also established a basis for including open research practices: 'the production of open research data should be acknowledged formally as a legitimate output of the research process and should be recognised as such by employers… in contributing to an individual’s professional profile in relation to promotion'.

Professor Marcus Munafò worked with members of the Programme Board and Academic Staff Development team to argue for the inclusion of open research practices in the Academic Promotions Framework, and developing the corresponding wording.

Those involved in the Programme Board were:

- Deputy Vice-Chancellor and Provost
- Chief People Officer
- Director of People and Organisational Development
- UCU Representatives
- Academic Representatives (Research, Educational and Leadership Improvement)
- Early Career Academic Representatives (Post-Doctoral Researcher and Lecturer)
- Staff Engagement Group Representative
- Head of Academic Staff Development

As the concept and practical resources for the Academic Promotions Framework evolved, there was also significant consultation across the institution for feedback. This included (but was not limited to) the following: 

- Heads of School across all Faculties
- Deans and Pro Vice Chancellors across all Faculties. 
- School Managers across all Faculties
- HR Business Partnering and Central HR Operations teams
- EDI Team
- Reward and Recognition Teams from Organisational Development
- People Development
- Trade Unions

For the Academic Promotions Framework to be adopted into practice, other changes were required, such as establishing a Faculty Promotions Committee for each Faculty. 

In particular, narrative writing workshops for building a promotion case within the Academic Promotions Framework were set up to help applicants understand the criteria and how to demonstrate that these had been met. This provided staff with the means and understanding for them to be recognised and rewarded appropriately, via a promotions case, both in general and specifically in relation to the inclusion of open research practices in their case if appropriate.

In the development of the Academic Promotion Framework, its concept was shared within the consultation groups (see above). This was via focus groups and bespoke presentations, led by the Academic Career Development Programme. 

The finalised versions of the Academic Promotions Framework are available to both internal colleagues and externally to the wider public via the University of Bristol website. As the APF versions evolved, this too was updated. The links to the Academic Promotions Framework, and associated guidance documentation were shared via internal bulletins, and by relevant line managers, School and Faculty staff and Heads of HR Business Partnering, as their colleagues prepared their promotion cases. 

The Academic Promotions Framework launched in time for the 2020/2021 promotions cycle for Associate Professor/Professor grades, and extended to Research/Teaching Associates through to Senior Lecturer/Senior Research Fellow grades in time for the 2021/2022 academic year. Shortly after the launch of the APF, the opportunity to use it to embed incentives for open research practices was recognised and pursued. The open research elements of the Academic Promotions Framework were promoted via the Research Improvement Group and through related activities such as the Open Research Prize.

## Challenges and lessons learnt

There was a need to make allowances for adjustments in Schools to support individual and discipline-specific requirements and approaches. This was particularly true for open research practices, which are adopted to different degrees currently across disciplines. Similarly, career stage was a consideration, as earlier-career researchers tend to be more familiar with open research practices than senior researchers.

Promotion is a topic which intersects several others across the institution. For effective changes to be made to the benefit of individuals and the institutional strategy, there must be meaningful consultation with all those who would be potentially impacted. 

The iterations that result from this consultation are made most effective when driven by a governance structure with clear accountability and responsibility of roles, working towards clearly defined objectives and timelines.

These issues are particularly salient in the context of open research practices, which are variably understood and engaged with across, for example, disciplines and career stage, meaning that the criteria needed to be sufficiently broad and flexible to accommodate this.

## Recommendations

- Senior Sponsorship is essential, and to provide direction and demonstrate institutional commitment.

- Clear governance structures for decision making are required, including a clear Responsibility, Accountability, Consulted and Informed (RACI) model for the delivery of the project.

- The inclusion of open research practices requires consideration of differences across, for example, disciplines and career stages, so that the relevant criteria are sufficiently broad and flexible.

- It is essential to have a full Equity Diversity and Inclusion impact assessment conducted and continuously reviewed throughout the project, and post-implementation. This will ensure representation across our full diversity of colleagues, and allow the impact of the process to be proactively assessed via reporting in areas such as: gender, ethnicity, contract status and career pathway.

## Resources

University of Bristol [Academic Promotions Framework](https://www.bristol.ac.uk/hr/policies/promotion/) 

© University of Bristol. Licensed under [CC BY](https://creativecommons.org/licenses/by/4.0/deed.en).
