
---
page-navigation: true
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    other-links:
      - text: This page as PDF
        href: resources/case-study-sunderland.pdf
        target: _blank
        icon: file-earmark-pdf
---

# Institutional commitment for open research: building awareness and buy-in to move towards reward and recognition at the University of Sunderland

**Delphine Doucet** (Research and Scholarly Communications Librarian)

See Implementation guide section: [Institutional Committment](https://recognition.ukrn-openresearch.ac.uk/guide-01-commitment.html)

## About the University of Sunderland

The University of Sunderland is a teaching intensive institution; however, our research activity is growing and embracing the principles of open research.  This aligns with the aim set out in our [Strategic Plan 2020-2025](https://www.sunderland.ac.uk/about/about-the-university/how-university-managed/strategic-plan-supporting-statements/strategic-plan/) of being society-shaping and producing impactful research. 

## What has changed?

As with many institutions, these are early days for building an open research culture within the University of Sunderland. Change is being championed by our Pro Vice Chancellor of Research and Global Engagement, Professor Jo Crotty. As we start to consider how we can make meaningful reform to reward and recognition practices, we need to ensure institution-wide commitment for open research, which includes the need to educate colleagues on what open research is and why it matters.

## Why was change undertaken?

The University has been a signatory of DORA since the academic year 2020/21 and has had an Open Access mandate since 2016. However, it was recognised that more was needed to embed open research practices in the University and that a stronger institutional commitment was necessary.

## How was the change carried out?

The first step the University undertook as part of its engagement with OR4 was to develop an Open Research Statement and a Responsible Use of Metrics Statement.  The two statements were drafted by the Research and Scholarly Communication Librarian. These drafts were developed by consulting similar statements available via other institutions’ websites such as Glasgow, Edge Hill, Sheffield Hallam, and Leeds universities. These drafts were then reviewed and amended by members of the academic community and staff in the Research and Graduate School team. The two statements were presented at our Research and Innovation Committee in June 2024 and after further amendments were adopted in September 2024.  

In addition to these statements of intent, we wanted to support and develop an understanding of open research in the institution. Using some funding from UKRI’s Enhancing Research Culture grant, the Research and Scholarly Communication Team (Libraries and Learner Development) led a small project to create training material to support staff and PGR understanding of open research. Our aim was to raise awareness, develop open research knowledge and skills in our research community, and align these with the University’s Open Research and Responsible Metrics statements. 

The funds were used to employ four PhD students to create training materials about open research to raise the baseline of understanding in the institution. The work also aimed to start an emerging advocacy strand and network for the institution about open research. 

## Challenges and lessons learnt

The four students created a range of materials to help advocate for open research (see resources below).

The materials were released in September 2024 via a Research Network meeting. The response was positive and staff who attended the meeting were keen to engage with the resources. In October 2024 we used International Open Access Week as another opportunity to promote the resources through the [University Library Research and Scholarly Communications Blog](https://libraryguides.sunderland.ac.uk/blogs/research-scholarly-communications/Blog), linking these clearly to our Open Research Statement. The four blog posts have been viewed regularly since they were posted with c.200 views between October 2024 and March 2025, and an increase in conversations with staff for the Research and Scholarly Communication Team (Libraries and Learner Development). 

In January 2025, a series of internal releases about the two statements were published with an offer of support and training  delivered by the Research and Scholarly Communication Team (Libraries and Learner Development). Each communication aimed to highlight specific elements of open research practices and link it with responsible metrics. Together they gathered c. 370 views. 

- Open Research and Responsible Use of Metrics 
- Open Research and Open Access 
- Open Research and Open Research Data 
- Open Research and Research Copyright 
- Open Research, pre-prints and preregistration 
- Open Research and engaged research 
- Open Research and open software 
- Responsible Metrics and assessing your research 

Contributing to our work of awareness raising, we co-organised  with the universities of Durham, Newcatle, Northumbria and Teesside an Open Research Week under the banner of the [Universities for North East England](https://blogs.ncl.ac.uk/opening-research/2025/02/universities-for-north-east-england-open-research-week-24-to-28-march-2025/). 

Further work will follow shortly with the release of a survey on open research (inspired by a survey of open research practices led at the University of Bristol) to understand training requirements for our staff. The survey was developed by one of our student interns. 

In the context of the current challenging financial situation for the HE sector and the demands placed on members of the University, it is certainly harder to communicate the importance of open research because it is just one of many completing pressures. The counterbalance is the REF and the opportunity to use PCE statements as a lever for research culture change. Activity is starting in this area. In particular, newly-appointed faculty research leads and unit of assessment leads will be key contacts and champions in supporting the adoption of open research practices. 

## Recommendations

- Context is everything - every institution is on a different path to open research and every step it takes to build understanding of open research practices is a step in the right direction
- Changing reward and recognition practices for open research is not something that can be done in silo, institutions must prioritise its benefits and advocate its importance to ensure institutional understanding and engagement.  However, by focusing on what you can change, it is possible to do interesting things that can ripple out and build momentum over time.

## Resources

University of Sunderland [An Open Research Game](https://libraryguides.sunderland.ac.uk/blogs/research-scholarly-communications/Blog/an-open-research-game)

University of Sunderland [Blog on Creative Commons Licenses](https://libraryguides.sunderland.ac.uk/blogs/research-scholarly-communications/Blog/cretive-common-licen) 

University of Sunderland [Blog on Opening Education Research during Open Access Week](https://libraryguides.sunderland.ac.uk/blogs/research-scholarly-communications/Blog/opening-education-research-oaweek)

University of Sunderland [Blog on 'Why' Open for Open Access Week](https://libraryguides.sunderland.ac.uk/blogs/research-scholarly-communications/Blog/why-open-research-oa-week)


© University of Sunderland. Licensed under [CC BY](https://creativecommons.org/licenses/by/4.0/deed.en).

