---
page-navigation: true
format:
  html:
    other-links:
      - text: This page as PDF
        href: resources/guide-summary.pdf
        target: _blank
        icon: file-earmark-pdf
---

# Executive summary

The importance and benefits of open research are widely accepted, and many institutions explicitly subscribe to open research principles. Policy drivers and compliance requirements related to open research are set to increase. But institutional commitments and open research policies are relatively unintegrated into research strategy, planning and management, and currently have limited influence on the behaviour of individual researchers. Systems of recognition and reward that operate in the recruitment, probation, promotion and appraisal of researchers can be powerful engines of behavioural change, but at present they do not effectively incentivise or reward open research practice. 

Open research practices should be a part of how researchers are assessed, because a researcher who uses such practices:

- better demonstrates, and enables verification of, the quality of their research; 
- facilitates re-use of the products of their research, in this way maximising their potential value and impact; 
- is able to provide a more representative picture of their research activities and outputs, enabling a more informed assessment of their capacity a a researcher. 

Operationalisation of open research incentives and expectations by research-performing organisations will signal that open practices are considered to be an essential part of how research is carried out. It will power the adoption of open research practices by researchers and lead to improvements in research integrity, quality and impact.

With momentum for research assessment reform building globally, there is an opportunity to integrate open research into revised researcher assessment frameworks and practices. Since the publication of the [San Francisco Declaration on Research Assessment](https://sfdora.org/read/) (DORA) in 2013, there has been an evolution in the research assessment reform agenda from an initial focus on responsible use of publication metrics towards a wider responsible research assessment framework. This has entailed increasing attention to elements related to research culture, research integrity and reproducibility, as represented most fully in the [Agreement on Reforming Research Assessment](https://coara.eu/) published in 2022 by the Coalition for Advancing Research Assessment (CoARA). 

This broader agenda is shaping the national research assessment framework in the UK as in other countries. The People, Culture and Environment element of the next Research Excellence Framework (REF) will include a greater emphasis on elements of research culture including open research. This is indicative of the direction of travel in the sector towards a more instrumental model of research assessment, which shapes the norms and ecxpectations associated with good research practice. Open research is an integral feature of good research practice as defineed by this model. 

Institutions therefore need to start developing researcher assessment policies to integrate recognition and reward for open research. This work will involve a number of challenges of implementation, which can be characterised at four levels: 

- **political**: getting buy-in from institutional leaders and managers and key stakeholders in professional services to support policy adoption and implementation across relevant procedures;
- **cultural**: securing assent from members of the research community in their capacity as both assessors and subjects of research assessment to the inclusion of open research in research assessment, and bringing about changes in practice; 
- **practical**: defining open research in such a way that instances of it can be demonstrated, identified, validated, and qualitatively evaluated within the context of an overall assessment, and providing the training and guidance that enables researchers and assessors to use the criteria effectively; 
- **operational**: implementing the changes to policies and procedures and underpinning systems, processes and support, creating and delivering guidance and training, and monitoring and managing compliance with implemented policies. 

The implementation guide addresses these aspects of implementation, with an emphasis on the political and cultural aspects in the earlier sections moving into the practical and operational aspects in the later sections. 
