---
page-navigation: true
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    # other-links:
    #   - text: This page as PDF
    #     href: resources/guide-06-support.pdf
    #     target: _blank
    #     icon: file-earmark-pdf
---

# 6. Support, systems and processes 

```{=html}
<a href="resources/guide-06-support.pdf"
   class="pdf-download" target="_blank"></a>
```

::: {.callout .feature}
Has support for open research recognition and reward been effectively operationalised in responsibilities of support staff, and administrative systems and processes?
:::

## Why is this important? 

- Implementation of procedures supporting recognition and reward for open research may involve changes to responsibilities of academic and professional services staff, and administrative systems and processes, and may entail reviewing resource requirements. Professional services support must be efficiently aligned to strategic objectives and any requirements for additional investment will need to be clearly justified.

- Staff responsible for supporting recognition and reward for open research may require training and oversight. Existing systems and processes may need to be revised, or new systems and processes implemented and integrated. 

## Maturity scale 

| No Action | Emerging | Evolving | Sustained |
|---------|---------|---------|---------|
| There is no operational implementation of recognition and reward for open research in research assessment. | Colleagues enabling open research provide some support for open research recognition and reward, without dedicated responsibilities, systems or processes. | In some research assessment activities, colleagues have defined responsibilities to support recognition and reward for open research, and there has been some development of supporting resources, systems and processes. | Colleagues have defined responsibilities to support recognition and reward for open research in relevant research assessment activities. Resources are allocated and supporting resources, systems and processes are well-developed and operating effectively. |

: {.sm .responsive .framework-table .framework-item}


## Progress actions 

Here are suggestions for key actions that can be taken to progress from one level of the maturity framework to the next. These can be considered when you develop an institutional action plan.  

### No Action to Emerging 

- Provide some informal ad hoc support for open research recognition and reward within existing professional services support roles and systems and processes. 

### Emerging to Evolving 

- Ensure that existing open research support roles provide some support for recognition and reward for open research in some defined researcher assessment processes.  

- Identify and develop areas of professional services support and changes to systems and processes necessary to implement recognition and reward for open research. 

### Evolving to Sustained 

- Demonstrate that professional services support for open research has developed, is well-integrated into institutional processes, and is delivering support in alignment with strategic objectives to grow open research culture and practice. 

- Ensure that relevant professional services staff have defined and understood responsibilities to support recognition and reward for open research as part of support for responsible research assessment and are delivering effective services.  

- Ensure that supporting systems and processes have been developed/implemented as required, are operating effectively, and are delivering timely support in response to demand. 

## Main areas of activity 

### Support 

There is likely to be growing need for both open research and responsible research assessment support as these become more integrated into business as usual and demand increases.  

Institutions will have some level of existing professional services support for open research. This may be focused on open access research publishing and research data management and sharing. Support may need to define a broader open research remit in accordance with strategic objectives to develop open research culture and practice, and additional staffing/resources may be required or desirable to meet a growing need for training and expert support across a variety of open research practices in addition to publishing and data sharing, e.g. research software engineering and pre-registration, and to provide discipline-specific expertise in open research methods. The senior strategic lead for open research and any relevant stakeholder group should work with professional services to develop strategic plans including business cases for investment where needed, expansion of roles to capture additional open research requirements, creation of partnership models and collaborative relationships, and more effective application of institutional expertise. What is achievable will depend on the avaialbility of resources in the institution.

There is likely also to be some existing support for the generation and validation of research metrics, as part of institutional research planning, management and assessment activities, and in response to the needs of individual researchers. Demand for these services can be expected to grow, with greater demand to handle enquiries, provide research metrics reports and researcher profiles, assess/validate metrics on request, and in other ways support those involved in research assessment activities, for example as part of recruitment or promotion panels. Monitoring and reporting on compliance with policy may require additional support. There will also be a need for institutions to work with their academic community to develop responsible assessment processes and provide guidance and training in responsible research assessment.  

There is work ongoing in the sector to develop indicators and metrics related to open research practices,^[GraspOS. <https://graspos.eu/>; OPUS. <https://opusproject.eu/>; UKRN (2023), 'UKRN 2nd working paper: Open Research Indicators: sector priorities'. <https://www.ukrn.org/2023/06/30/ukrn-2nd-working-paper-open-research-indicators-sector-priorities/>.] and this may be an area where there will be a need for new responsibilities related to their collection and management. Other new demands may also be established, including training for panels or guidance on job descriptions and narrative CVs. 

Colleagues providing support for processes such as recruitment, probation, promotion and performance and development review may need to integrate some support for responsible research assessment, and recognition of open research within that. Additional requirements may be absorbed into existing responsibilities, processes and systems to a large extent. For example, HR staff may need to check job advertisements and job descriptions against requirements; or if there is a requirement for members of recruitment and promotion panels to take training on responsible research assessment, training logs may need to be created and checked. HR colleagues will also need to be sufficiently informed to handle enquiries that may require signposting of relevant policy or information, or making a referral to expert support, for example as provided by open research support colleagues.  

### Systems and processes  

Systems and processes may need to be modified or developed in support of changes to research assessment policies and procedures. For example: 

- Forms may need to be updated, e.g. to include instructions and guidance on citation of open research activities and outputs other than publications where relevant; 

- Templates may need to be updated to include standard texts related to responsible research assessment and open research expectations for use in job advertisements; 

- Research assessment workflows and checklists may need to be developed, to help staff undertake research assessment appropriately. This could include open research-related checks; 

- New systems, or developments to existing systems, and related processes may to be required to collect and process open research information. This is dealt with in more detail below. 

### Collecting and managing open research information 

Developments in research infrastructure are making it easier to identify and collect outputs and data related to individuals and organisations. Information about open research activities and outputs can be used to support institutional planning and development, to manage and report against compliance requirements, and to inform researcher assessments. Institutions may need to adapt existing systems or invest in new solutions and integrate them with their existing research information infrastructure. 

Key developments in research infrastructure directly relevant to capturing and processing information about open research activities and outputs include increasing use of: 

- trustworthy repositories to publish and preserve different kinds of outputs; 

- persistent identifiers (PIDS) such as DOIs and ORCiDs to enable accurate citation, discovery and linking of entities (e.g. linking of researchers and institutions to research outputs, and linking between research outputs, such as publications and datasets); 

- the [CRediT Contributor Roles Taxonomy](https://credit.niso.org/) in output metadata, facilitating more accurate description of individual contributions to research activities and outputs. 

Publishers and other providers of research infrastructure services are developing research information and analytics products to enable the aggregation, management and analysis of data about open research outputs (including data, code, protocols, pre-registrations, preprints) and attributes (e.g. CRediT roles) from across a distributed research infrastructure of publisher platforms, repositories, preprint servers, registries, broker services and research information systems. Examples of products that support open research analytics include [Dimensions](https://www.dimensions.ai/products/) from Digital Science, Elsevier's [Data Monitor](https://www.elsevier.com/en-gb/products/data-monitor), and [OpenAIRE Monitor](https://monitor.openaire.eu/). The PLOS Open Science Indicators initiative, developed in collaboration with the AI company Dataseer, is working to develop and pilot institution-level reporting functionality.^[PLOS (2023), 'The new Open Science Indicators dataset is here!' <https://theplosblog.plos.org/2023/10/open-science-indicators-q2-2023/>.]   

One important aspect for institutions to consider is the openness of research information. It is a principle of responsible research assessment that those being evaluated should be able to verify the data and analysis used to evaluate them. Yet much of the information by which research practices might be monitored and evaluated is held in closed systems. Proprietary commercial products such as Web of Science and Scopus, which underpin much of the publication-based analytics used in researcher assessment activities, lack transparency. This is something that has been of concern to the research assessment reform movement, with DORA, the Leiden Manifesto and CoARA all taking positions in support of open research information.  The [Barcelona Declaration on Open Research Information](https://barcelona-declaration.org/), published in 2024, sums up the concerns of the sector and enumerates a set of commitments that signatories can sign up to.  

Some institutions are developing their own workflows and services to collect and manage open research information. For example, the University of Manchester Library has developed an [Open Research Tracker](https://www.openresearch.manchester.ac.uk/support/tracker/), which leverages integrations with its CRIS, CrossRef, and the Scholarcy AI platform to collate and integrate information about publications and data. Its development roadmap anticipates further integrations, including with its data repository, ORCiD, the Open Science Framework, and protocols.io, and the capability to collect data relating to a wider range of output types, including pre-registrations, methodologies, and research software. The University is planning to release its software under an Open Source licence, so that other institutions can make use of it. 

