---
page-navigation: true
format:
  html:
    number-sections: true
    number-offset: 0
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    # other-links:
    #   - text: Maturity Framework
    #     href: resources/04_0r4-resourcepack-maturityframework-v2.pdf
    #     target: _blank # opens in a new tab
    #     icon: file-earmark-pdf # https://icons.getbootstrap.com/
---

# Institutional commitment

<!-- last pare of research assessment reform section, link to guide intro should go to subsection Open research and research assessment reform -->

::: {.callout .feature}
Does your institution make public commitments to the principles and aims of open research and responsible research assessment, which are aligned to the direction of travel in the sector and supported by effective action? 
:::

## Why is this important? 

- Expressions of institutional commitment can send a strong message that open research and responsible research assessment are matters of strategic importance to the institution and its leadership. 

- The process of consulting on and formulating a statement of commitment can engage key stakeholders and create a shared sense of purpose and strategic direction, providing a foundation for effective action. 

- The institution can ensure that recognition and reward for open research is within the scope of research assessment reform and that where strategic action on open research and research assessment reform are separately undertaken, activity leads/groups are agreed on common objectives and co-ordinated in their activities. 

- Public alignment to influential statements such as the UNESCO Recommendation on Open Science, DORA and CoARA signals that the necessity for cultural change is widely accepted in the sector and that the institution and its members must adapt. Membership of CoARA provides access to working groups that can support sharing of good practice and implementation. 

## Maturity scale 

<!--Add row of maturity framework as table-->

| No Action | Emerging | Evolving | Sustained |
|--------|---------|---------|---------|
| <span>There are no public institutional commitments to open research and responsible research assessment.</span> | <span>There are public institutional commitments to open research and responsible research assessment but little or no recognition of open research in research assessment practice.</span> | <span>There are public institutional commitments to open research and responsible research assessment. There is an explicit commitment to recognise and reward open research in research assessment practice.</span> | <span>Public open research and responsible research assessment commitments are well-integrated into recognition and reward policies and procedures. There is a strong shared understanding of how open research and responsible research assessment contribute to institutional research strategy and overall mission.</span> |

: {.sm .responsive .framework-table .framework-item}

## Progress actions 

Here are suggestions for key actions that can be taken to progress from one level of the maturity framework to the next. These can be considered when you develop an institutional action plan.  

### No Action to Emerging 

- Adopt and publish an open research statement. 

- Adopt and publish a commitment to the implementation of responsible research assessment. This could be held within the wider open research statement. 

- Sign the Agreement on Reforming Research Assessment and join the Coalition on Advancing Research Assessment (CoARA) and communicate this within the institution. 

### Emerging to Evolving 

- Initiate action to implement commitments, e.g. by appointment of senior strategic leads for open research and responsible research assessment, development and publication of action plans, and engagement of key stakeholders. 

- Include a commitment to recognise and reward open research practice within institutional research assessment. 

- Ensure senior leads and stakeholder groups (where they have been established) are co-ordinated towards objectives for recognition and reward for open research.  

- Demonstrate that progress has been made in implementing commitments, e.g. by publishing updates against action plan milestones. 

### Evolving to Sustained 

- Ensure that commitments are well-integrated into relevant policies, procedures, assessment, guidance and training, and that they are widely understood and supported by research leaders and managers. 

- Ensure that activities and communications relating to institutional research strategy, environment and culture are aligned to and reference institutional commitments. 

## Main areas of activity 

### Open research statement 

Increasing numbers of UK universities, and indeed institutions globally, are adopting public institutional statements of commitment to the principles and aims of open research.^[Sheppard, N. (2020, since updated), 'Open access is not enough: reproducible science, research and scholarship'. UKCORR. Blogpost. <https://www.ukcorr.org/2020/12/02/open-access-is-not-enough-reproducible-science-research-and-scholarship/>.]  Their function is to provide the strategic commitment to develop a culture of open research and the high-level framework under which activity and policies (such as those on open access and data sharing) can sit. The statement should be in alignment with (and may reference) the University's research strategy.  

It is preferable for the statement to include a commitment to recognise and reward open research practice within institutional assessment. It should reference an institutional statement or policy on responsible research assessment this exists. Reference to statements such as the [UKRI position on open research](https://www.ukri.org/what-we-do/supporting-healthy-research-and-innovation-culture/open-research/) and the [UNESCO Recommendation on Open Science](https://www.unesco.org/en/open-science/about?hub=686) can serve to emphasise alignment to the sector. 

Members of the institution formulating this commitment will need to reflect on how open research is understood within the context of the institutional mission, and how it contributes to the advancement of that mission. 

### Research assessment reform  

With momentum for research assessment reform building globally, many institutions are reviewing or planning to review their research assessment policies and procedures. This may entail publishing or refreshing a statement of commitment to the agenda of research assessment reform.  

Many institutions have already signed the [San Francisco Declaration on Research Assessment](https://sfdora.org/read/) (DORA) and will have made a commitment to improve research and researcher assessment within their institutions. As of 7th November 2022, DORA asked signatory institutions to 'share a public statement detailing their commitment to DORA and responsible research assessment to their communities'.^[DORA (2022), 'Engagement and outreach policy'. <https://sfdora.org/sign/>.]   

Whether or not institutions are DORA signatories, there is a case for signing the Agreement on Reforming Assessment to begin the process of establishing specific commitments and a timetable of reform. Signatories commit to develop and share with CoARA within one year of signing the Agreement an [action plan](https://coara.eu/agreement/action-plan/) for reviewing or developing criteria, tools and processes in line with the core Commitments. They also agree to regularly demonstrate progress against this action plan, with a touch point within five years of signing the Agreement.  

Institutions that receive funding from the [Wellcome Trust](https://wellcome.org/grant-funding/guidance/open-access-guidance/research-organisations-how-implement-responsible-and-fair-approaches-research) are also required to publish on their website a commitment to the use of responsible research assessment aligned with the DORA and CoARA principles. They are expected to have a plan in place for implementing the principles, and for monitoring and reporting on implementation. 

A statement of institutional commitment to research assessment reform should include an undertaking to integrate open research criteria into systems of reward and recognition, in line with the emphasis placed on open research/open science in the Agreement and [more recent discussions of responsible research assessment](guide-intro.qmd). It should also reference the statement of institutional commitment to open research, where this exists. 

### Supporting commitments 

Aside from commitment explicitly based on or subscribing to the main research assessment reform initiatives, institutions might consider making supporting commitments, e.g.: 

- The [More than Our Rank](https://inorms.net/more-than-our-rank/) initiative provides an opportunity for academic institutions to highlight the problematic nature of league table rankings.  

- the Hidden REF 5 % Manifesto encourages institutions to commit to submit at least 5% of their submissions to REF 2029 as non-traditional research outputs, to promote better representation for the range of research contribution roles and 'non-traditional' research outputs. 

Whether or not institutions sign up to all these commitments, discussion of them can be useful ways to highlight areas of practice in need of reform and to consider ways in which they might be addressed. 

### Building commitment 

Publishing commitments to open research or research assessment reform will be a collective effort, with stakeholder groups led by senior colleagues. Any commitment will be ineffective if the effort is not made to build the coalition that will implement it and if ownership and accountability are not built in. The process of developing an institutional statement will offer an opportunity to engage stakeholders through consultation, to secure support for their achievement through strategic actions. Care should be taken to ensure that relevant stakeholder groups are represented in the process of developing and consulting on institutional commitments (including, for example, early career researchers and professional services colleagues) and that statements, once adopted, are communicated to the research community. Institutional commitments will need to be signed off at a high level, and there will need to be appropriate ownership of, and accountability for, delivering against the commitments. 

Strategic activities related to development of open research and research assessment reform may have separate origins within the institution and may be undertaken by separate groups under different leadership. Where this is the case, it will be important to ensure that their activities are co-ordinated on the common ground of reward and recognition for open research, and that there is agreement about objectives and the means of attainment. The process of developing and consulting on institutional statements should ensure this co-ordination and agreement take place.  

Agreement on the relevance and place of open research within research assessment cannot be taken for granted. One advantage of signing up to the Agreement on Reforming Research Assessment is that by doing so the institution subscribes to the Core Commitment to 'Recognise the diversity of contributions to, and careers, in research in accordance with the needs and nature of the research'. The purpose of this Commitment is to broaden the range of research activities and outputs recognised, to include inter alia 'diverse outputs beyond journal publications' and 'practices that contribute to robustness, openness, transparency and the inclusiveness of research'.  

### Demonstrating progress in implementing the commitments 

The institution will need to demonstrate over time that aspirational commitments are being realised and incorporated into business as usual. Published commitments can identify senior leads and groups responsible for implementing them, and include action plans and updates on progress against milestones. Where there are specific reporting expectations associated with external commitments, such as those associated with membership of [CoARA](https://coara.eu/agreement/action-plan/), these can be communicated within the institution.  

Activities and communications relating to institutional research strategy, environment and culture should be aligned to and reference institutional commitments. Policies and procedures will in due course integrate elements of the open research commitments that have been realised and may reference them, as may relevant guidance and training. Internal communication channels can be used to communicate the open research commitments to key stakeholders and the broader research community. Management structures can be used to ensure the commitments are applied and referenced as appropriate.  

## Case studies 

Coming soon!

