---
page-navigation: true
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    other-links:
      - text: This page as PDF
        href: resources/guide-07-training.pdf
        target: _blank
        icon: file-earmark-pdf
---

# 7. Guidance and training 

::: {.callout .feature}
Do you provide guidance and training on recognition and reward for open research for the benefit of colleagues involved in activities that require the assessment of researchers, such as recruitment, probation, promotion and performance and development review, and for researchers subject to assessment, some of whom will be external? 
:::

## Why is this important? 

- For change to be effective and sustained, those affected will need guidance and training to help them understand policy requirements, their responsibilities, and how to meet them. This will apply both to those involved in the assessment of researchers and those being assessed. 

- Criteria and methods of assessment must be transparent and accessible to those subject to assessment. 

- Guidance and training can contribute to cultural change by developing understanding, knowledge and motivation to adopt the desired practices. 

## Maturity scale 

| No Action | Emerging | Evolving | Sustained |
|---------|---------|---------|---------|
| There is no guidance or training on recognition and reward for open research in research assessment. | Some guidance on recognition and reward for open research is provided for those involved in research assessment. | Guidance and training on recognition and reward for open research is well-developed and made available to researchers, assessors and external candidates, as relevant. Resources are integrated into some processes and are promoted to staff. Training is encouraged for key staff members. | Guidance and training on recognition and reward for open research is available for all relevant groups. It is systematically targeted at staff involved in research assessment, and integrated into auditable training and development frameworks and processes. There is widespread use of training. |

: {.sm .responsive .framework-table .framework-item}


## Progress actions 

Here are suggestions for key actions that can be taken to progress from one level of the maturity framework to the next. These can be considered when you develop an institutional action plan.  

### No Action to Emerging 

- Publish information and/or provide ad-hoc training on recognition of open research in research assessment. 

### Emerging to Evolving 

- Provide publicly accessible guidance on recognition of open research as part of guidance supporting research assessment. 

- Provide research assessment training including consideration of recognition and reward for open research that is available to all members of staff. 

- Encourage completion of research assessment training for key categories of staff, e.g. researchers' line managers, members of recruitment and promotion panels.  

### Evolving to Sustained 

- Link to guidance and training on research assessment including consideration of recognition and reward for open research from all relevant policies and procedures. 

- Integrate research assessment training into professional development frameworks, e.g. for early career researchers. 

- Make research assessment training required for some colleagues, e.g. members of recruitment and promotion committees, with completion logged and monitored using institutional systems. 

## Main areas of activity 

### Guidance  

Guidance on recognition and reward for open research will need to be provided in the context of guidance to support responsible research assessment in accordance with institutional policy. Employees involved in assessment activities will need to be sufficiently informed to be able to undertake assessment following the required processes and using appropriate assessment criteria and methods. Guidance will need to be linked to policy and integrated into systems and processes, so that it is signposted at relevant stages. It will need to explain the principles of research assessment, and the criteria and methods by which assessment is to be undertaken.  

Transparency about assessment criteria and methods is essential. Candidates for assessment, whether applicants for jobs from outside the institution, colleagues undergoing probation or annual performance review, or those applying for promotion, will need to be sufficiently informed about assessment criteria and methods to be able to present their track records appropriately and effectively. Guidance will need to be publicly accessible online, so that it can be referred to by job applicants.  

This guidance will need to include appropriate discussion of the recognition of open research in assessment, and to link to any open research statement, supporting information, and sources of support. Given that awareness and understanding of open research and appropriate practices for presenting, identifying and assessing evidence of open research practice are likely to be relatively undeveloped, guidance will need to be supportive in these respects, and to provide relevant illustrations. This might cover, for example: 

- defining open research, in terms of types of practices and outputs that could be cited as evidence, and characteristics of good practice, e.g. sharing of outputs using open and standard licences, use of sustainable infrastructure such as repositories and persistent identifiers, conformity to FAIR Principles;

- publishing and/or linking to case studies of open research practice across different fields, so that researchers can identify practices relevant to their discipline and type of research. The UK Reproducibility Network provides an extensive compendium of [open research across disciplines](https://www.ukrn.org/disciplines/). A number of institutions have also published open research case studies, in some cases genereated through open research award initiatives.^[See e.g. Keele: <https://www.keele.ac.uk/research/raise/governanceintegrityandethics/researchintegrity/openresearch/openresearchcasestudies/>; Leeds: <https://leedsunilibrary.wordpress.com/2022/12/09/open-research-case-studies-by-faculty/>; Manchester: <https://www.openresearch.manchester.ac.uk/resources/case-studies/>; Newcastle: <https://www.ncl.ac.uk/library/academics-and-researchers/research/open-research/case-studies/>; Reading: <https://www.reading.ac.uk/research/research-environment/open-research/open-research-case-studies>; Sheffield: <https://www.sheffield.ac.uk/openresearch/casestudies>; Surrey: <https://www.surrey.ac.uk/library/open-research/case-studies>; UCL: <https://www.ucl.ac.uk/library/open-science-research-support/open-science/about-office-open-science-scholarship/open-science-case>.] 

- specifying the criteria by which evidence of open research will be assessed, and its role within the overall assessment, in alignment with the institution's research assessment policy; 

- providing guidance on how to cite a variety of open research outputs across a range of disciplines and types of research, with examples of good citation practice; 

- illustrating how a narrative presentation of track record might demonstrate the value of open research activities and outputs, through evidence of use, reach and impact, provided in accordance with responsible research assessment principles; 

- signposting further information and support. 

### Training  

Training in responsible research assessment including consideration of recognition and reward for open research should be provided for staff undertaking assessment and for those preparing to go through a formal assessment process. This should cover the same ground as the guidance, and should be integrated into procedures, for example, so that recruitment and promotion committee members and candidates for promotion are directed to the training at appropriate points.  

Training should be available for all staff involved in assessment activities and could be made mandatory in some cases: for example, it could be required for all line managers of researchers, for all members of academic recruitment and promotion committees, and for all candidates for academic promotion. Training may be delivered as an e-learning course to provide a basic level of understanding at scale, and as online or face-to-face sessions to develop more in-depth knowledge and skill. Records of completion of training maintained in institutional training systems can be used to monitor compliance. Where staff are involved in assessment activity and fail to complete required training this can be followed up with appropriate action. Training logs can also provide an indicator of the degree to which policy and understanding of responsible research assessment have been disseminated across the institution, and so provide one of the measures for ongoing monitoring. 

Training in responsible research assessment and presentation of open research track record could also be incorporated into institutional professional development frameworks, for example for early career researchers. 

