---
page-navigation: true
format:
  html:
    number-sections: true
    number-offset: 1
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
---

# Leadership 

::: {.callout .feature}
Does your institution provide leadership at a senior level for strategic action on open research and responsible research assessment, including recognition and reward for open research, and is open research leadership fostered at all levels in the institution? 
:::

## Why is this important? 

- Recognition and reward for open research may be implemented at the intersection of strategic activities to develop open research culture and to undertake research assessment reform. Where these activities are separately led, leaders in both areas must accept and agree on the objectives to be achieved, in order for implementation to be effective. 

- Recognition and reward for open research in research assessment is relatively undeveloped. There is a risk that the importance of recognising and rewarding open research will not be appreciated or factored into activity. It will be essential to have an informed and empowered advocate who is able to ensure open research is within scope of activity and given due weight.  

- Leadership can be demonstrated by those in positions of influence, as research leaders and managers and senior members of professional services, as colleagues who might support good practice though the provision of services, guidance and training e.g., organisational culture or HR representatives, and as informal or nominated advocates of open research.  

## Maturity scale 

:::{.column-page}

| No Action | Emerging | Evolving | Sustained |
|---------|---------|---------|---------|
| There is no senior strategic leadership for open research or responsible research assessment. | There are identified senior strategic leads for open research and responsible research assessment. Recognition and reward for open research in research assessment is an identified priority for strategic action. | Senior leadership develops actions on open research and responsible research assessment in collaboration with key stakeholders. Actions to recognise open research in research assessment are agreed and supported by relevant leads and promoted by open research advocates across the institution. | Recognition and reward for open research in research assessment is progressed as a strategic priority by members of senior management. External engagement ensures alignment to sector. Leadership in open research is seen and valued across the organisation, and includes researchers, research enablers and open research advocates. |

: {.sm .responsive .framework-table .framework-item}

:::

## Progress actions 

Here are suggestions for key actions that can be taken to progress from one level of the maturity framework to the next. These can be considered when you develop an institutional action plan.  

### No Action to Emerging 

- Nominate and empower a member of senior management or professional services with responsibility for strategic action to develop open research culture and practice. 

- Nominate and empower a senior strategic lead for responsible research assessment.  

- Identify recognition and reward for open research as a priority for strategic action. 

## Emerging to Evolving 

- Evidence sustained activity by senior strategic leads for open research and responsible research assessment and engagement with relevant stakeholders. Where leadership of open research and responsible research assessment is separate, ensure there is co-ordinated actions and agreement on objectives to include recognition and reward for open research. 

- Identify and develop advocates in the research community and professional services who can provide leadership and support for open research recognition and reward. 

## Evolving to Sustained 

- Demonstrate progress in embedding culture change under the direction of the senior strategic lead. 

- Cascade open research leadership through the organisation, with research leaders and managers, research professionals and other champions showing leadership in open research in their areas of activity and influence.  

- Demonstrate that championing open research practice is a recognised criterion of research leadership, for example through inclusion in job descriptions, promotion criteria, annual performance and development review. 

- Demonstrate that leadership in the institution is engaging externally with research assessment reform networks in order to promote effective recognition and reward for open research at a national level. 

## Main areas of activity 

### Open research leadership 

A member of senior management with responsibility for developing open research culture and practice within the institution can develop and lead strategic action and act as a senior champion for open research. This person will represent the institutional commitment to open research and act as a strong advocate for the open research interest. They must be sufficiently informed about open research and convinced of its importance to be a strong advocate. This will be essential where research assessment reform activity is separately led, and discussion may be required to ensure that recognition and reward for open research is within scope of activity and given appropriate weight. 

An open research lead is likely to have greatest impact when this is a role with authority to instigate institution-wide change e.g., a dean, senior professional services manager, or someone at a similar level. It is preferable for the role to have some FTE commitment with defined responsibilities and accountability, for example to develop, implement and report on the progress of a plan of strategic action to increase open research culture and practice in the institution. For members of the UKRN, the role could fit well with that of Institutional Lead: members of the UKRN are required to appoint a senior academic to this role, with responsibility for research improvement and research integrity, reporting to the PVC for Research (or their equivalent). The Institutional Lead role is expected to make a minimum commitment of 1 day per week (0.2FTE). Stakeholders within institutions that lack an open research lead and are not currently members of UKRN may be able to use the case for membership as a vehicle for securing senior management leadership for open research.  

Action to develop open research culture and practice in the institution would ideally be undertaken by a group convened for the purpose under the senior lead for open research and comprising representatives of key stakeholder groups, including representatives of the academic community and relevant professional services. However, the scope of this group, and its actions, are anticipated to vary across institutions based upon research priorities and available resources. 

### Leadership in recognition and reward for open research  

Implementation of recognition and reward for open research will require leadership in promoting the need for change within the institution, engaging key stakeholders and the wider community to secure buy-in and manage resistance, and in managing a stakeholder group tasked with delivering established objectives. 

Implementation may sit at the intersection of otherwise separate activities to address research assessment reform and to develop open research culture and practice. These activities may be undertaken by separate groups under the direction of different senior leads within the institution. Where this is the situation, the lead for open research will need to make the case for recognition of open research within institutional assessment and ensure that there is agreement with the lead for research assessment reform on the objectives to be achieved and the means by which they will be achieved. This agreement may have been established through the process of developing institutional commitments to open research and research assessment reform. 

### External engagement 

While the focus of senior leadership roles will be on activity within the institution, there will also be opportunities for external engagement. Leadership here may help to promote alignment in policies for recognition of open research within research assessment, at the level of national assessment (i.e. through the REF), by funders when assessing researchers and institutions for the award of grants, and between institutions, so that researchers are assessed by similar standards at all institutions. Representation in national fora such as the [CoARA National Chapter](https://coara.eu/coalition/national-chapters/coara-national-chapter-uk-2/) (for CoARA members) and the OR4 Community of Practice afford opportunities to exchange knowledge and practice and to co-ordinate activities across the UK sector. 

### Research leaders and managers 

Research leaders and managers have a role to play in developing a research environment that incentivises researchers to use open research practices, as well as in the specific promotion of recognition and reward for open research. According to their roles and institutional requirements they may do any of the following: 

- promote the use of open research practices in the areas under their authority, including relevant policy expectations, such as those relating to open access publication and data sharing; 

- set an example by demonstrating good open research practice in their own work and professional relationships; 

- use communication activities to highlight and celebrate the open research activities and outputs of colleagues; 

- engage with and signpost to colleagues the professional services that provide support for open research, such as research publishing and research data management services; 

- support researchers at all levels to develop their knowledge and skills through the training and support provided by the institution; 

- use research planning and internal review processes to identify and if required report on attainment of open research objectives at group or individual level, as relevant; 

- monitor activity and compliance, and take appropriate action in cases of non-compliance or poor practice, such as arranging for additional support or training;  

- ensure that activities involving the assessment of researchers under their authority (e.g. recruitment and probation, promotion, performance and development review, etc.) implement appropriate recognition and reward for open research. 

### Other leadership roles 

Leadership will also be required at different levels and in different places in the institution to champion the open research agenda, and specific activity to include recognition and reward for open research in research assessment. Champions may be: 

- Members of professional services who will support implementation: both those who provide open research support and training and have a strong investment in promoting open research practice, and others such as HR professionals who may have specific roles to play in implementing and promoting new policies and procedures; 

- Advocates for good practice in research, who may be formally nominated in some capacity, or have some informal role. Examples include open research champions, UK Reproducibility Network Local Network Leads, etc.    


