---
title: Implementation guide
page-navigation: true
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
---

The implementation guide provides detailed guidance for institutions on implementing effective recognition and reward for open research in researcher assessment. The guide is illustrated with case studies from institutions that have participated in the OR4 project. It can be used by a group of stakeholders to develop a shared understanding of the rationale for recognising and rewarding open research practice and to explore different aspects of implementation in greater depth, in order so support informed planning and implementation. It can be used in conjunction with the [maturity framework](maturity-framework.qmd) and as part of an institutional self-assessment exercise.

An [executive summary](guide-summary.qmd) provides a high-level overview of the context and rationale for strategic action and the main areas of implementation covered by the guide. This providesa a useful one-pager for those who want a summary of the essentials.

The introductory section, [Why recognise and reward open research practice?](guide-intro.qmd) explains the rationale for strategic action with reference to the wider sector context in more detail. This is a more developed treatment of the subject and can be used by members of a stakeholder group to establish a shared understanding and sense of purpose.

The nine sections mapped to the action areas of the maturity framework are designed to enable members of the stakeholder group to develop a more in-depth understanding of the key areas in which action may be required, and to create a practical plan of action to develop institutional maturity. 

A [Glossary of key terms](glossary.qmd) is also included.

Each of the nine main sections of the guide follows a standard format:

- **Why is this important?**
- **Maturity scale**: the maturity scale for this action area
- **Progress actions**: suggested key actions to move from one level of maturity (as defined by the maturity framework) to the next
- **Main areas of activity**: in-depth guidance
- **Case studies**: links to case studies illustrating different aspects of implementation at UK institutions


