---
page-navigation: true
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    other-links:
      - text: This page as PDF
        href: resources/guide-03-strategy.pdf
        target: _blank
        icon: file-earmark-pdf
---

# 3. Strategy and planning

::: {.callout .feature}
Do you have a strategic plan owned by a stakeholder group for developing open research culture and practice, and is recognition and reward for open research addressed in this plan and any related policies/plans concerning the assessment of researchers? 
:::

## Why is this important? 

- Recognition and reward for open research practice must be situated within wider strategic activity to develop open research culture and practice in the institution. Researchers may lack awareness of open research or the motivations, skills and resources to effectively adopt open research practices. 

- Implementing recognition and reward for open research should be a key element of research assessment reform.  

- Implementing expectations related to open research in research assessment will not be effective if the institution does not also develop policy and infrastructure, and provide information, training and support to create an environment in which open research practice is enabled and incentivised. 

## Maturity scale 

| No Action | Emerging | Evolving | Sustained |
|---------|---------|---------|---------|
| There is no open research strategy or plans to implement change. | A strategic plan for open research has identified recognition and reward for open research in research assessment as an area for action. This objective is recognised in strategic action on research assessment reform. | Strategic action on open research has progressed. Recognition and reward for open research across all key areas of research assessment is actioned by a stakeholder group against a strategic plan. Progress has been made against objectives. | Strategic action on open research is well-developed and sustained. Recognition and reward for open research has been implemented in relevant policies and procedures. The implementation plan has been delivered and action is focused on monitoring, consolidating and embedding practice. |

: {.sm .responsive .framework-table .framework-item}


## Progress actions 

Here are suggestions for key actions that can be taken to progress from one level of the maturity framework to the next. These can be considered when you develop an institutional action plan.  

### No Action to Emerging 

- Create and secure approval for a strategic action plan to develop open research culture and practice which identifies recognition and reward for open research as an area for action. 

- Where research assessment reform work is undertaken by an existing group, ensure that there is representation for open research in this group. 

- Establish recognition and reward for open research as an objective, and discuss the infrastructure, training, and support that may be required. 

### Emerging to Evolving 

- Demonstrate progress against an open research action plan. 

- Ensure there is a detailed plan for implementing research assessment reform, including recognition and reward for open research, which is agreed and owned by the relevant stakeholder group. 

- Demonstrate progress against the research assessment reform implementation plan, with members of the stakeholder group working to deliver primary objectives.  

### Evolving to Sustained 

- Demonstrate that substantive progress has been made against the action plan to develop open research culture and practice. 

- Demonstrate that primary objectives of the research assessment reform plan have been delivered, with recognition and reward for open research integrated into relevant research assessment policies and procedures. 

- Move from implementation to consolidation and embedding of operational activity, with monitoring and reporting to the relevant oversight committee/group. 

## Main areas of activity 

### Open research action plan 

A strategic action plan to develop open research culture and practice may be created and implemented. The plan is likely to identify objectives, deliverables, timelines, responsibilities and measures of attainment, and will require a commitment of staff time and other resources required for effective implementation. The plan will need to be managed on an ongoing basis, and able to demonstrate and report progress against specified milestones to a relevant committee.^[UKRN provides a 'Checklist for an Open Research Action Plan': <https://www.ukrn.org/primers/>. Examples of plans developed by different institutions include: Keele, <https://tinyurl.com/2wehf9xr>; Reading, <https://tinyurl.com/murfjnf2>; Surrey, <https://tinyurl.com/5n7mtbe2>.] It should include as one of its objectives to promote and suppot the implementation of recognition and reward for open research. 

Implementation of recognition and reward for open research may not be directly owned by an open research stakeholder group, as it may sit within wider activity related to research(er) assessment. An open research lead should ensure that relevant open research objectives are within the scope of research assessment reform activity and are appropriately defined and represented in this group.  

Recognition and reward for open research will be one primary objective of the open research strategic plan, which will be enabled by more general progress in developing the culture and practice of open research in the institution. As open research is progressively established in the mainstream of institutional research activities, and as open research practice increases, it will become more usual for researchers to evidence the use of open research practices when presenting their work, and for this to be expected and recognised by those involved in the assessment of researchers.  

### Implementing recognition and reward for open research in research assessment reform 

Within plans for research assessment reform, recognition and reward for open research should be included. This is likely to affect many areas of assessment activity, including the development of policy and procedures, and any guidance, training and support. Open research expertise will be necessary to ensure open research is fully integrated into the implementation plan and that these elements are delivered as work progresses. For this reason, where open research and research assessment reform are separetely led strategic activities within an institution, effective representation for the open research interest will be essential. 

Recognition and reward for open research can be addressed as part of planning to meet the first Core Commitment of the [Agreement on Reforming Research Assessment](https://coara.eu/agreement/the-agreement-full-text/), to 'Recognise the diversity of contributions to, and careers, in research in accordance with the needs and nature of the research'. The purpose of this Commitment is to broaden the range of research activities and outputs recognised, to include *inter alia* 'diverse outputs beyond journal publications' and 'practices that contribute to robustness, openness, transparency and the inclusiveness of research'. This Commitment can be linked to the 'Diversity, inclusiveness and collaboration' Principle, which discusses a wide range of research outputs and explicitly mentions open science practices. 


