
:::{.column-body-outset}
# A toolkit for recognising and rewarding open research 

The **Recognising and rewarding open research** toolkit is designed to help universities and other research-performing organisations implement effective recognition and reward for open research through researcher assessment practices. It can support institutions to develop researcher assessment policies and practices that incentivise, enable and increase the use of open research practices by their researchers. 

The toolkit has been produced by the [Open and Responsible Researcher Reward and Recognition Project](about.html) (OR4). OR4 is part of the UK Reproducibility Network’s [Open Research Programme](https://www.ukrn.org/open-research-programme/), which aims to accelerate the uptake of open research practices across the UK Higher Education sector.  

Here's a quick 7-minute introductory video explaining the toolkit and how to navigate it: 

<iframe width="560" height="315" src="https://www.youtube.com/embed/bmzDy5ziJxk?si=rxce0tAfZ385abXs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Who is the toolkit for? 

The toolkit is intended for use by institutional leaders and other stakeholders who are or may be involved in making the case for and implementing recognition and reward for open research within the institution's researcher assessment processes. 

It may also be a useful reference for those involved in the management and ongoing operational support of recognition and reward for open research. 

## Scope of the toolkit 

The toolkit is concerned with introducing appropriate [recognition and reward](glossary.html#recognition-and-reward) for open research in institutional [researcher](glossary.html#researcher) assessment practices. Activities within scope include the recruitment and probation of researchers, promotion and professorial review, performance and development review, internal funding processes, and any other operations involving the assessment of researchers and groups of researchers. It will also be relevant to institutional research strategy and planning. 

Many research organisations have in recent years embarked on strategic activity to develop open research culture and practice. Many are also considering or engaged in a process of research assessment reform aligned to the principles of responsible research assessment exemplified in the [San Francisco Declaration on Research Assessment](https://sfdora.org/read/) (DORA) and the [Agreement on Reforming Research Assessment](https://coara.eu/agreement/the-agreement-full-text/). The toolkit sits at the intersection of these two areas. The framework for action presented here supports effective recognition of the diversity of a researcher's activities and outputs and of open research practice in accordance with the principles of responsible research assessment.  

## Contents of the toolkit 

The main components of the toolkit are: 

* a [maturity framework and self-assessment tool](maturity-framework.html) that institutions can use to assess their maturity in the implementation of relevant policies and practices, to support internal discussion and planning, and to measure ongoing progress; 

* an [implementation guide](guide-contents.html) consisting of an introduction and sections linked to corresponding action areas in the maturity framework, providing detailed practical guidance to support assessment of institutional maturity, planning and progress. The guide is illustrated with [case studies](case-studies.html) that exemplify different aspects of institutional activity. 

The toolkit will continue to evolve throughout the OR4 project (until 2027), as guidance is updated and new case studies are published. 

Visit the [toolkit overview](overview.html) to find out more. 
:::
