---
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
    other-links:
      - text: Maturity framework
        href: resources/or4-maturityframework.pdf
        target: _blank # opens in a new tab
        icon: file-earmark-pdf # https://icons.getbootstrap.com/
      - text: Self-assessment tool
        href: resources/or4-selfassessment.docx
        target: _blank # opens in a new tab
        icon: file-earmark-word # https://icons.getbootstrap.com/
---

# The OR4 maturity framework

The maturity framework and self-assessment tool can be used by a group of stakeholders in an institution to assess maturity in the implementation of recognition and reward for open research, to support internal discussion and planning, and to measure ongoing progress. 

The maturity framework describes four levels of maturity across nine action areas:

- **No Action**: There is currently no action in this area
- **Emerging**: There is some developing activity in this area, but it is relatively unsystematic and lacking in strong strategic direction
- **Evolving**: Activity is developing in a systematic and strategic fashion in this area and is demonstrating progress against defined objectives 
- **Sustained**: Activity has implemented its main strategic objectives and is consolidating and embedding on a business-as-usual basis.

| Action Area | No Action | Emerging | Evolving | Sustained |
|--|---|---|---|---|
| [Institutional commitment](guide-01.qmd) | <span>There are no public institutional commitments to open research and responsible research assessment.</span> | <span>There are public institutional commitments to open research and responsible research assessment but little or no recognition of open research in research assessment practice.</span> | <span>There are public institutional commitments to open research and responsible research assessment. There is an explicit commitment to recognise and reward open research in research assessment practice.</span> | <span>Public open research and responsible research assessment commitments are well-integrated into recognition and reward policies and procedures. There is a strong shared understanding of how open research and responsible research assessment contribute to institutional research strategy and overall mission.</span> |
| [Leadership](guide-02.qmd) | <span>There is no senior strategic leadership for open research or responsible research assessment.</span> | <span>There are identified senior strategic leads for open research and responsible research assessment. Recognition and reward for open research in research assessment is an identified priority for strategic action.</span> | <span>Senior leadership develops actions on open research and responsible research assessment in collaboration with key stakeholders. Actions to recognise open research in research assessment are agreed and supported by relevant leads and promoted by open research advocates across the institution.</span> | <span>Recognition and reward for open research in research assessment is progressed as a strategic priority by members of senior management. External engagement ensures alignment to sector. Leadership in open research is seen and valued across the organisation, and includes researchers, research enablers and open research advocates.</span> |
| [Strategy and planning](guide-03.qmd) | <span>There is no open research strategy or plans to implement change.</span> | <span>A strategic plan for open research has identified recognition and reward for open research in research assessment as an area for action. This objective is recognised in strategic action on research assessment reform.</span> | <span>Strategic action on open research has progressed. Recognition and reward for open research across all key areas of research assessment is actioned by a stakeholder group against a strategic plan. Progress has been made against objectives.</span> | <span>Strategic action on open research is well-developed and sustained. Recognition and reward for open research has been implemented in relevant policies and procedures. The implementation plan has been delivered and action is focused on monitoring, consolidating and embedding practice.</span> |
| [Communication and engagement](guide-04.qmd) | <span>There is no communication about the recognition of open research in research assessment.</span> | <span>Some information about recognition and reward for open research in research assessment has been communicated, but with little or no guidance, or active engagement.</span> | <span>Strategic communications about recognition and reward for open research are part of an open research communication plan. Key stakeholders have been identified and engaged. Stakeholders have been able to learn about and contribute to changes in policy and procedure.</span> | <span>Well-publicised information about recognition and reward for open research in research assessment policies and procedures is supplemented by strategic, consistent communications targeting key stakeholders and the wider community to raise awareness and promote good practice.</span> |
| [Policy and procedure](guide-05.qmd) | <span>Recognition and reward for open research is not referenced in policies or procedures related to or involving the use of research assessment.</span> | <span>Recognition and reward for open research is mentioned in some relevant policies and procedures, but on a limited basis and with little evidence of integration or effective use.</span> | <span>Recognition and reward for open research is included in most relevant policies, with evidence of effective integration into practice. </span> | <span>Recognition and reward for open research is included in all relevant policies and procedures. There is evidence of increasing effective use of open research criteria by candidates and assessors in research assessment activities. Policies are reviewed regularly.</span> |
| [Support, systems and processes](guide-06.qmd) | <span>There is no operational implementation of recognition and reward for open research in research assessment.</span> | <span>Colleagues enabling open research provide some support for open research recognition and reward, without dedicated responsibilities, systems or processes.</span> | <span>In some research assessment activities, colleagues have defined responsibilities to support recognition and reward for open research, and there has been some development of supporting resources, systems and processes.</span> | <span>Colleagues have defined responsibilities to support recognition and reward for open research in relevant research assessment activities. Resources are allocated and supporting resources, systems and processes are well-developed and operating effectively.</span> |
| [Guidance and training](guide-07.qmd) | <span>There is no guidance or training on recognition and reward for open research in research assessment.</span> | <span>Some guidance on recognition and reward for open research is provided for those involved in research assessment.</span> | <span>Guidance and training on recognition and reward for open research is well-developed and made available to researchers, assessors and external candidates, as relevant. Resources are integrated into some processes and are promoted to staff. Training is encouraged for key staff members.</span> | <span>Guidance and training on recognition and reward for open research is available for all relevant groups. It is systematically targeted at staff involved in research assessment, and integrated into auditable training and development frameworks and processes. There is widespread use of training.</span> |
| [Monitoring and evaluation](guide-08.qmd) | <span>There is no monitoring or evaluation of recognition and reward for open research in research assessment.</span> | <span>There has been some observation of practice with respect to recognition and reward for open research in research assessment.</span> | <span>Measures are defined and reported to monitor use of open research criteria in research assessment, with some operational support. Data capture developments in some practices and/or identifies areas for targeting.</span> | <span>There is systematic collection and reporting of data on use of open research criteria in research assessment,  with allocated operational support. Progress is monitored and evaluated across the institution, identifying and targeting areas for improvement.</span> |
| [Research planning](guide-09.qmd) | <span>Open research is not considered in institutional and individual research planning activities.</span> | <span>There is some use of open research criteria in institutional and individual research planning activities, but these are not fully aligned with institutional research and assessment strategies.</span> | <span>Open research criteria are defined and reported in institutional and individual research planning activities. Planning identifies open research objectives and links these to institutional strategy related to open research and recognition and reward.</span> | <span>Open research criteria are systematically used and reported in institutional and individual research planning activities. There is evidence of a sustained increase in setting and reporting against open research objectives. Strategic priorities related to open research inform institutional planning.</span> |

: Maturity Framework (under construction) {.sm .responsive .framework-table}


## The OR4 self-assessment tool

An assessment undertaken using the maturity framework and the self-assessment tool will generate an overall picture of institutional maturity across all nine action areas at a given point in time. It can enable a group of stakeholders to establish a baseline, identify and focus on the target level of maturity in each action area, plan the means by which this target can be attained, and in due course to measure progress.

How you use the materials is entirely up to you, but we recommend a self-assessment exercise be built around a workshop for a group of stakeholders. The workshop will be most effective if it is established on the basis of a shared understanding of the open research and research assessment reform agendas and the rationale for implementing recognition and reward for open research. The introduction to the implementation guide, [Why recognise and reward open research practice?](guide-intro.qmd), could be read by participants in preparation for the workshop. The [nine sections of the guide](guide-contents.qmd) mapped to the maturity framework can be used to develop a more in-depth understanding of the action areas and to identify key progress actions that can inform the action plan developed in the workshop.

## Template for a self-assessment exercise

### Before the workshop

Identify the group of stakeholders who will participate in the exercise, and the person who will facilitate the session. It may help all members of the group participate on an equal footing if the facilitator is someone independent from the group.

Ask each member of the stakeholder group to:

1. Read the introductory section,  [Why recognise and reward open research practice?](guide-intro.qmd) and spend some time browsing the [guide](guide-contents.qmd). This is to ensure all members of the group have a shared understanding and sense of purpose around recognition and reward for open research
2. Undertake an independent assessment of institutional maturity using the maturity framework as a reference. The related sections of the guide can be used to explore each action area in greater depth and identify relevant progress actions. The self-assessment tool can be used to document maturity assessments for each of the nine action areas, along with comments and notes on the progress actions the institution should take.

### The workshop

We recommend the workshop is no longer than 2 hours. The workshop can be used to:

-	agree on the current level of maturity in each of the action areas
-	identify the level of maturity you would like to reach over a given timescale (e.g. 2-3 years later)
-	identify progress actions necessary to attain the target maturity level, and organise these into the framework for a strategic plan.

The workshop could follow a four-stage format:

1. Introduction.  A set of slides is provided which can be used to set the scene and explain to the group why incorporating recognition and reward for open research into researcher assessment is important. The slides can be freely adapted. 
2. Breakout groups/discussion 1: 
    a. discuss individual institutional assessments for each of the nine areas
    b. compare notes
    c. agree current and target maturity levels for each of the nine areas
3.	Breakout groups/discussion 2:
    a. identify priorities and areas for change
    b. identify and organise progress actions to achieve previously agreed target maturity levels for each of the sections
4.	Wrap-up: 
    a. summarise the discussions
    b. set next steps and allocate actions 

### After the workshop

1. Write up the summary of the exercise
2. Develop a draft action plan 
3. Schedule a date to re-run the assessment, e.g. at project conclusion or a milestone stage identified in the plan), in order that progress can be measured and celebrated, and a plan for further action agreed if required.

[Download maturity framework PDF](resources/or4-maturityframework.pdf)

